### ISSUE TITLE
Password match does not work

### ISSUE THREAD

**Issue by clemens-huebner** [clemens-huebner/amos-ss16-proj8#12]
The app does not test if the passwords are equal.
Luong, you worked on this, can you fix this?

**Comment by trungluongquang** [comment]
I fixed it and make it more readable by moving custom directive "validateMatch" from controllers.js to a new directives.js file. Changes also made in index.html, app.js

the problem was the missing usage of validate-match = "pw1"

commited to 23-create-account

**Comment by clemens-huebner** [comment]
@trungluongquang Nice, thanks you for the fast solution!
