### ISSUE TITLE
Bug_2016-07-07_showing Login

### ISSUE THREAD

**Issue by Najmeddineaskri** [clemens-huebner/amos-ss16-proj8#160]
when we pushed My Account on the menu we get the login page, the way how to get this page is not so nice. we get at first the edit-account page then login page.
It would be better to get only login page, when the account button is pushed.

**Comment by trungluongquang** [comment]
frankly, I do not think what @Najmeddineaskri mentions above is a bug but just an improvement. The bug here is when you are in login page and click back, you will go to Edit Account page and cannot go to login page again

**Comment by Najmeddineaskri** [comment]
@trungluongquang are you serious !!!!

**Comment by Najmeddineaskri** [comment]
@trungluongquang did you know an app who, when you pushed login you get other page at first ?

**Comment by trungluongquang** [comment]
I'm serious. However, you can call this issue by any name you want. In my opinion, if you have time, you should focus on the bug of back button in login page rather than trying to make it look nicer. I need to deliver an app which functions well enough by deadline, not a perfect-looking app

**Comment by clemens-huebner** [comment]
I think, it is not a real bug, but it would be easier to solve the thing Najm mentions that handling the back button. So I agree with Najm (on the objective things).
