### ISSUE TITLE
Bug_2016-07-12_Android-Participant list

### ISSUE THREAD

**Issue by trungluongquang** [clemens-huebner/amos-ss16-proj8#211]
@muradIsa 
I cannot download or email participant list on Android
this function works very well on iPhone

I use an administrator user to test

**Comment by muradIsa** [comment]
@trungluongquang did you try to download it using Phonegap, if so, it was already mentioned that Phonegap doesn't support some plugins (file opener and email composer plugin as well). Just checked it with built apk file, works fine on Android.

**Comment by trungluongquang** [comment]
I build it in mojo-ci.cs.fau.de and install on my phone

**Comment by muradIsa** [comment]
Just tested with downloaded from our artifact download apk file. Works fine.
User: admin
Event: Event with address
Please also provide more detailed information about your test. Which user and which event was it?

**Comment by trungluongquang** [comment]
user: luongadm@gmail.com / Vinamilk12
event: Event With Address

iPhone: works
android: does not work

2016-07-12 14:07 GMT+02:00 Murad notifications@github.com:

**Comment by muradIsa** [comment]
Strange. Tested with the same user and the same event. Both Email and Download worked on Android.

**Comment by trungluongquang** [comment]
could you test the send email to contact? If it works on your device, it
means the problem is my device (may be OS version, Email application,...)

2016-07-12 14:20 GMT+02:00 Murad notifications@github.com:

**Comment by clemens-huebner** [comment]
It's not working for me, too.
I'm pretty sure it has something to do with device.

**Comment by muradIsa** [comment]
It is probably because of that you don't have external SD card on your device.
