### ISSUE TITLE
Bug_2016-07-12_Push Notification

### ISSUE THREAD

**Issue by trungluongquang** [clemens-huebner/amos-ss16-proj8#212]
Nothing happens when I click on Reminder / An Event erinnern button

as I check on console, the status code is 500 Internal Server Error

event: Event novem - 33b0a2da-655c-4ebe-b840-9349abe98f64

@clemens-huebner @muradIsa any ideas?

**Comment by trungluongquang** [comment]
this function works well with event c0d9f7e7-9f0e-4694-886f-f66ca44ea4f8 (Wvent with ....)

something strange

**Comment by trungluongquang** [comment]
i found the problem. You cannot send push-notification if in the participant list, there is an user with username "admin"

**Comment by clemens-huebner** [comment]
I will add a bugfix for that

**Comment by clemens-huebner** [comment]
Found another solution (Luong found it ;) ) so it's fine.
