### ISSUE TITLE
Bug_2016-06-07_empty event section 

### ISSUE THREAD

**Issue by clemens-huebner** [clemens-huebner/amos-ss16-proj8#57]
When there are no upcoming/previous/todays events, this should be handled: either not showing the section at all or showing a note that there are no events there @KatharinaGrasser: What do the POs prefer?

**Comment by KatharinaGrasser** [comment]
I would prefer showing a note, but I want to also discuss the issue with Marina, thus we will give you the final answer tomorrow

**Comment by KatharinaGrasser** [comment]
As discussed, a note should be displayed in case of no events in one of the sections
