### ISSUE TITLE
 Bug_2016-06-07_remember login 

### ISSUE THREAD

**Issue by clemens-huebner** [clemens-huebner/amos-ss16-proj8#58]
We still have the "remember login" checkbox without functionality. Delete it or build the functionality? @KatharinaGrasser

**Comment by KatharinaGrasser** [comment]
Please build the function and make sure, that username and password are not remembered in case the "remember login" button is not pushed

**Comment by clemens-huebner** [comment]
@KatharinaGrasser Is not trivial, so please add it to the backlog

**Comment by KatharinaGrasser** [comment]
I included it in the product backlog. It is user story 58 right now and on the end of our priorities because at the moment this function is not crucial.

**Comment by clemens-huebner** [comment]
Implemented with pull request #127
