### ISSUE TITLE
Bug_2016-06-19_insert new question

### ISSUE THREAD

**Issue by KatharinaGrasser** [clemens-huebner/amos-ss16-proj8#94]
After inserting a new live voting question, the 'going back' arrow in the upper left corner is no longer available.

**Comment by trungluongquang** [comment]
There is three more issues with this function:
- Testing device: iPhone 5s
- Decription:
- cannot scroll down or scroll up so when the list of questions is so long, a user cannot click on Insert button
- the first question does not show properly on iPhone 5s screen (the same problem as first button of menu)
- although there are already some questions on the list, the notification "There are no questions yet" still appears
